import type { Intent } from "@geoffcox/pretty-good-nlp";

export const coffeeIntent: Intent = {
  name: "Add coffee order",
  examples: [
    {
      name: "Could I have an iced grande vanilla latte",
      parts: [
        {
          name: "order intent",
          phrases: [
            "Could I have",
            "Could I please have",
            "I would like",
            "I\'d like",
            "I'd love",
            "Please",
            "Please give me",
            "Please make me",
            "Make me",
            "Give me",
            "Gimme",
            "I will have",
            "I'll have",
            "I want",
            "Make",
            "Brew",
            "Add",
            "Plus",
          ],
        },
        {
          name: "quantity",
          phrases: ["a", "an", "one", "two", "three", "four", "five", "six"],
          regularExpressions: ["\\d+"],
          variable: "quantity",
          weight: 0,
        },
        {
          name: "size",
          phrases: [
            "short",
            "tall",
            "grande",
            "venti",
            "small",
            "medium",
            "large",
            "extra large",
            "8 ounce",
            "8 oz",
            "12 ounce",
            "12 oz",
            "16 ounce",
            "16 oz",
            "20 ounce",
            "20 oz",
          ],
          variable: "size",
          ignoreOrder: true,
        },
        {
          name: "flavors",
          phrases: ["vanilla", "hazelnut", "caramel", "raspberry"],
          variable: "flavor",
          weight: 0,
          ignoreOrder: true,
        },
        {
          name: "temperature",
          phrases: [
            "hot",
            "cold",
            "iced",
            "extra hot",
            "room temperature",
            "tepid",
          ],
          variable: "temperature",
          weight: 0,
          ignoreOrder: true,
        },
        {
          name: "product",
          phrases: [
            "cocoa",
            "chocolate",            
            "espresso",
            "espressos",
            "latte",
            "lattes",
            "americano",
            "americanos",
            "cappuccino",
            "cappuccinos",
            "macchiato",
            "macchiatos",
            "mocha",
            "mochas",
            "drip",
            "drips",
            "drip coffee",
            "drip coffees",
            "coffee",
            "coffees",
            "brewed coffee",
            "brewed coffees",
          ],
          required: true,
          variable: "product",
        },
      ],
      neverParts: [
        {
          name: "negations",
          phrases: [
            "don't",
            "do not",
            "won't",
            "will not",
            "cancel",
            "nevermind",
          ],          
        },
      ],
    },
  ],
};
