import type { Intent } from "@geoffcox/pretty-good-nlp";

export const coffeeIntent: Intent = {  
  name: "Add coffee drink",
  examples: [
    {
      canonicalForm: "<order intent> <quantity> <size> <flavor> <drink>",
      parts: [
        {
          phrases: [
            "Could I have",
            "I would like",
            "I'd like",
            "I'd love",
            "Please",
            "Please give me",
            "Please make me",
            "Make me",
            "Give me",
            "Gimme",
            "I will have",
            "I'll have",
            "I want",
            "Make",
            "Brew",
          ],
        },
        {
          phrases: ["a", "one", "two", "three", "four", "five", "six"],
          regularExpressions: ["\\d+"],
          variable: "quantity",
        },
        {
          phrases: [
            "short",
            "tall",
            "grande",
            "venti",
            "small",
            "medium",
            "large",
            "extra large",
            "8 ounce",
            "8 oz",
            "12 ounce",
            "12 oz",
            "16 ounce",
            "16 oz",
            "20 ounce",
            "20 oz",
          ],
          variable: "size",
        },
        {
          phrases: ["vanilla", "hazelnut", "caramel", "raspberry"],
          variable: "flavor",
          weight: 0,
        },
        {
          phrases: ["hot", "cold", "iced", "extra hot", 'room temperature', 'tepid'],
          variable: "temperature",
          weight: 0,
        },
        {
          phrases: [
            "cocoa",
            "espresso",
            "espressos",
            "latte",
            "lattes",
            "americano",
            "americanos",
            "cappuccino",
            "cappuccinos",
            "macchiato",
            "macchiatos",
            "mocha",
            "mochas",
            "drip",
            "drips",
            "drip coffee",
            "drip coffees",
            "coffee",
            "coffees",
            "brewed coffee",
            "brewed coffees",
          ],
          variable: "product",
        },
      ],
    },
  ],
};
